apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-java-app
  template:
    metadata:
      labels:
        app: demo-java-app
    spec:
      containers:
        - name: demo-java-app
          image: wunnahtun99/demo-java-app:latest  # Docker image on Docker Hub
          ports:
            - containerPort: 8080  # Ensure this matches the port Spring Boot listens on
