apiVersion: v1
kind: Service
metadata:
  name: demo-java-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001  # You can choose a port in the range 30000-32767
  selector:
    app: demo-java-app


